{{- if .Values.configmap.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "universal.fullname" . }}
{{- with .Values.configmap.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
