{{- if eq .Values.app.kind "Deployment" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "universal.fullname" . }}
  namespace: {{ include "universal.namespace" . }}
  labels:
    {{- include "universal.labels" . | nindent 4 }}
    {{- with .Values.app.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.app.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ if not (eq .Values.app.replicas "") }}{{ .Values.app.replicas }}{{ else }}{{.Values.app.replicaCount }}{{ end }}
  revisionHistoryLimit: {{ .Values.app.revisionHistoryLimit }}
  {{- with .Values.app.strategy }}
  strategy:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "universal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "universal.selectorLabels" . | nindent 8 }}
        {{- with .Values.app.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- .Values.app.podAnnotations | toYaml | nindent 8 }}
    spec:
      {{- include "universal.pod" . | nindent 6 }}
{{- end }}
