{{- if .Values.service.headlessService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "universal.fullname" . }}-headless
  namespace: {{ include "universal.namespace" . }}
  labels:
    {{- include "universal.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  selector:
    {{- include "universal.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}