{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "universal.fullname" . }}
  namespace: {{ include "universal.namespace" . }}
  labels:
    {{- include "universal.labels" . | nindent 4 }}
    {{- with .Values.secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ .Values.secret.type }}
{{- with .Values.secret.data }}
data:
  {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}