{{- if eq .Values.app.kind "StatefulSet" }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "universal.fullname" . }}
  namespace: {{ include "universal.namespace" . }}
  labels:
    {{- include "universal.labels" . | nindent 4 }}
    {{- with .Values.app.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.app.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.app.replicas (not .Values.app.autoscaling.enabled) }}
  replicas: {{ .Values.app.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "universal.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "universal.fullname" . }}-headless
  template:
    metadata:
      labels:
        {{- include "universal.selectorLabels" . | nindent 8 }}
        {{- with .Values.app.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- .Values.app.podAnnotations | toYaml | nindent 8 }}
    spec:
      {{- include "universal.pod" . | nindent 6 }}
  {{- with .Values.app.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
