{{- if eq .Values.app.kind "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "universal.fullname" . }}
  namespace: {{ include "universal.namespace" . }}
  labels:
    {{- include "universal.labels" . | nindent 4 }}
    {{- with .Values.app.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.app.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "universal.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "universal.fullname" . }}-headless
  template:
    metadata:
      labels:
        {{- include "universal.selectorLabels" . | nindent 8 }}
        {{- with .Values.app.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.configmap.enabled }}
        {{- $_ := set .Values.app.podAnnotations "checksum/config" (include (print $.Template.BasePath "/configmap.yaml") . | sha256sum) }}
        {{- end }}
        {{- if .Values.secret.enabled }}
        {{- $_ := set .Values.app.podAnnotations "checksum/secret" (include (print $.Template.BasePath "/secret.yaml") . | sha256sum) }}
        {{- end }}
        {{- .Values.app.podAnnotations | toYaml | nindent 8 }}
    spec:
      {{- include "universal.pod" . | nindent 6 }}
  {{- with .Values.app.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
